export { kurtSentences }

// omit punctuation at the end of sentences
let kurtSentences = [
  "We are what we pretend to be, so we must be careful about what we pretend to be",
  "Those who believe in telekinetics, raise my hand",
  'Of all the words of mice and men, the saddest are, "It might have been"',
  "Dear future generations: Please accept our apologies. We were rolling drunk on petroleum",
  "Here we are, trapped in the amber of the moment. There is no why",
  "I tell you, we are here on Earth to fart around, and don't let anybody tell you different",
  "True terror is to wake up one morning and discover that your high school class is running the country",
  "Like so many Americans, she was trying to construct a life that made sense from things she found in gift shops",
  "I was a victim of a series of accidents, as are we all",
  "Science is magic that works",
  "If you can do no good, at least do no harm",
  "We are healthy only to the extent that our ideas are humane",
  "You can't just eat good food. You've got to talk about it too. And you've got to talk about it to somebody who understands that kind of food",
  "Wake up, you idiots! Whatever made you think that money was so valuable?",
  "I think you guys are going to have to come up with a lot of wonderful new lies, or people just aren't going to want to go on living.",
  "She was a dull person, but a sensational invitation to make babies",
  "Another flaw in the human character is that everybody wants to build and nobody wants to do maintenance",
  "I am eternally grateful for my knack of finding in great books, some of them very funny books, reason enough to feel honored to be alive, no matter what else might be going on",
  "We're terrible animals. I think that the Earth's immune system is trying to get rid of us, as well it should",
  "All right, I'll tell you what you did for me: you went for happy, silly, beautiful walks with me",
  "Everything is nothing, with a twist",
  "Americans... are forever searching for love in forms it never takes, in places it can never be. It must have something to do with the vanished frontier",
  "If your brains were dynamite there wouldn't be enough to blow your hat off",
  "She hated people who thought too much. At that moment, she struck me as an appropriate representative for almost all mankind",
  "Maturity...is knowing what your limitations are...Maturity is a bitter disappointment for which no remedy exists, unless laughter can be said to remedy anything",
  "And a step backward, after making a wrong turn, is a step in the right direction",
  "If I am going to spend eternity visiting this moment and that, I'm grateful that so many of those moments are nice",
  "We could have saved the Earth but we were too damned cheap",
  "There are too many of us and we are all too far apart",
  "I can have oodles of charm when I want to",
  "Round and round we spin, with feet of lead and wings of tin",
  "All of the true things I am about to tell you are shameless lies",
  "If you can do a half assed job of anything, you're a one eyed man in a kingdom of the blind",
  "You'll forget it when you're dead, and so will I. When I'm dead, I'm going to forget everything and I advise you to do the same",
  "Enjoy the little things in life because one day you`ll look back and realize they were the big things",
  "A saint is a person who behaves decently in a shockingly indecent society",
  "I really wonder what gives us the right to wreck this poor planet of ours",
  "It was very exciting for her, taking his dignity away in the name of love",
  "Of course it is exhausting, having to reason all the time in a universe which wasn't meant to be reasonable",
  "As Bokonon says: peculiar travel suggestions are dancing lessons from god",
  "If what Jesus said was good, what can it matter whether he was God or not?",
  "We are what we pretend to be, so we must be careful about what we pretend to be",
  "We are what we imagine ourselves to be",
  "Life is no way to treat an animal",
  "The truth is, we know so little about life, we don't really know what the good news is and what the bad news is",
  "New knowledge is the most valuable commodity on earth. The more truth we have to work with, the richer we become",
  "I still catch myself feeling sad about things that don't matter anymore",
  "Well, here we are, Mr. Pilgrim, trapped in the amber of this moment. There is no why",
  "When everything was beautiful and nothing hurt",
  "As stupid and vicious as men are, this is a lovely day",
  "Eat, drink, and be merry, for tomorrow we die",
  "All persons, living and dead, are purely coincidental",
  "No art is possible without a dance with death",
  "All people are insane. They will do anything at any time, and God help anybody who looks for reasons",
  "Seems like the only kind of job an American can get these days is committing suicide in some way",
  "Everything about life is a joke. Don't you know that?",
  "No art is possible without a dance with death, he wrote",
  "Only in books do we learn what's really going on",
  "There's only one rule that I know of, babies—God damn it, you've got to be kind",
  "How embarrassing to be human",
  "The insane, on occasion, are not without their charms",
  "Fucking was how babies were made",
  "You realize, of course, that everything I say is horseshit",
  "Earthlings went on being friendly, when they should have been thinking instead",
  "profanity and obscenity entitle people who don't want unpleasant information to close their ears and eyes to you",
  "The champagne was dead. So it goes",
  "There is no peace, I'm sorry to say. We find it. We lose it. We find it again. We lose it again",
  "I have had all I can stand of not taking myself seriously",
  "Please, a little less love, and a little more common decency",
  "Cigarettes are a classy way to commit suicide",
  "I wish you'd help me look into a more interesting problem, namely my sanity",
  "Of all the words of mice and men, the saddest are, “It might have been",
  "The most heartbreakingly beautiful girl I ever hope to see",
  "The function of the artist is to make people like life better than they have before",
  "Symbols can be so beautiful, sometimes",
  "Everyone now knows how to find the meaning of life within himself",
  "Only nut cases want to be president. This was true even in high school. Only clearly disturbed people ran for class president",
  "Because of the movies nobody will believe that it was babies who fought the war",
  "Being an American means never having to say you're sorry",
  "There is nothing left of him but curiosity and a pair of eyes",
  "Take care of the people, and god almighty will take care of himself",
  "See the cat? See the cradle?",
  "Sometimes I wonder about the Creator of the Universe",
  "How nice to feel nothing, and still get full credit for being alive",
  "I hate it that Americans are taught to fear some books and some ideas as though they were diseases",
  "Love is where you find it. I think it is foolish to go looking for it, and I think it can often be poisonous",
  "We are here to help each other get through this thing, whatever it is",
  "Among the things Billy Pilgrim could not change were the past, the present, and the future",
  "I could carve a better man out of a banana",
  "There is room enough for an awful lot of people to be right about things and still not agree",
  "Perhaps I am the turtle, able to live simply anywhere, even underwater for short periods, with my home on my back",
  "No damn cat, and no damn cradle",
  "It is never a mistake to say goodbye",
  "Our government's got a war on drugs. That's certainly better then no drugs at all",
  "Pretend to be good always and even God will be fooled",
];

let kurtSentencesTest = [
  "ree",
  "ree",
  'ree',
  "ree",
  "ree",
];